# 
# docker-compose.yml — определяет сервисы для разработки и тестирования.


services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bankdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: bankdb
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: changeit1234567890changeit1234567890
      AES_KEY: 0123456789abcdef
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  db_data: