#
# application.yml — главный конфигурационный файл Spring Boot.

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bankdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml
  web:
    resources:
      add-mappings: false

# Actuator settings
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      enabled: true
      show-details: when_authorized
    info:
      enabled: true

# Swagger configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

app:
  jwt:
    secret: ${JWT_SECRET:abcdefgh1234567890abcdefgh1234567890abcdefgh1234567890}
    expirationMs: 86400000
  aes:
    key: ${AES_KEY:0123456789abcdef0123456789abcdef}

logging:
  level:
    com.example.bankcards: DEBUG
    org.springframework.security: DEBUG
